version: '3'
services:
  strapi:
    image: strapi/strapi:3.6.8-node14
    container_name: strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./backend:/srv/backend
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres:11.13-stretch
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./prostgres:/var/lib/postgresql/data
  frontend:
    image: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - '3000:3000'
    stdin_open: true
    depends_on:
      - strapi