version: '3.9'

services:
 strapi:
   image: strapi/strapi:3.6.8-node14
   container_name: strapi
   restart: always
   volumes:
     -  /srv/app

 frontend:
   build:
     context: ./frontend
     dockerfile: Dockerfile
   image: frontend
   container_name: frontend
   volumes:
     - /srv/frontend
