name: 'Deploy docker compose Heroku' #set whatevername you want to your github job
on: {
      workflow_dispatch:
      push:
        - branchs:
            main
} # set the events you would like to trigger this job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          docker_compose_file: './src/docker-compose.heroku.yml' # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"strapi","appname":"portalforartists","apptype":"web"},{"imagename":"frontend","appname":"portalforartists","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type
